Add hubverse retreat photo and description to "who we are" page
hubverse-org/hubDocs pull request #144
Opened 2024-07-09 12:19 UTC by mmkerr

Add hubverse retreat photo and description to "who we are" page

2024-07-09 13:23 UTC, mmkerr commented
@Nick Since I was on this page, I noticed we didn't have the CFA award listed. I went ahead and added it. Is this okay?

2024-07-10 15:59 UTC, nickreich commented on docs/source/overview/who-we-are.md
> +Our annual “hubverse retreat” was held June 3-7, 2024 at the University of Massachusetts, Amherst. This year’s retreat focused on the future of hubs in the cloud, dashboarding, and the archiving of h
could we change "annual" to "second annual"?

2024-07-10 16:00 UTC, nickreich commented on docs/source/images/hubverse-retreat.png
The image is small on the page. Can we load in a larger version so that it appears larger on a laptop screen? I looked at the preview site and the image took up about half of the content column width.

2024-07-10 16:00 UTC, nickreich requested changes
Thanks for adding this content! Few small changes requested.

2024-07-10 16:52 UTC, harryhoch commented
I fixed a small issue with the headers - the build complained that headers went from H1 to H3, so I changed the H3 to H2. Otherwise looks fine.

2024-07-11 12:47 UTC, mmkerr commented
Thank you for reviewing @nickreich and @harryhoch. @nickreich I have made the requested changes.

2024-07-11 21:04 UTC, nickreich approved these changes
Thanks for the updates. LGTM!

2024-07-11 21:04 UTC, merged