add a who and a why to the docs
hubverse-org/hubDocs pull request #172
Opened 2024-08-22 21:55 UTC by zkamvar

This is my attempt at giving readers a way to connect to the material. 

"The best way to know the correct answer to something is to come up with the wrong one first"

I know I have gotten concepts wrong and they need to be corrected!

2024-08-26 18:46 UTC, nickreich commented on docs/source/overview/who-uses-hubverse.md
> +A **modelling hub** consists of a **hub administrator** who is responsible for coordinating model submissions from **modellers** who submit **model outputs** in a standardized format defined by the h
... one or more hub administrators...?

2024-08-26 19:03 UTC, nickreich requested changes
This is a great start at filling in a gaping hole in the documentation. I've left some comments throughout plus the comment below.

In addition to the roles listed here, we also should include "Analyst" as someone who consumes the data from a hub. This person might want to look at the [accessing data from a hub vignette](https://hubverse-org.github.io/hubData/articles/connect_hub.html) from hubData, or maybe learn about building ensembles, or just understand about the different formats of data and model output types.

2024-08-26 19:03 UTC, nickreich commented on docs/source/overview/who-uses-hubverse.md
> +## Modellers
other things I think we want to include as possible things modelers might want to do:
- understand the definitions of and differences between model outputs
- understand the [structure of model output datasets](https://hubverse-org.github.io/hubData/articles/connect_hub.html#structure-of-hubverse-datasets)
- build ensembles using hubEnsembles

2024-08-26 20:12 UTC, zkamvar commented on docs/source/overview/who-uses-hubverse.md
> +The goal of the hubverse is to **ensure decision makers have model summaries they can trust** by facilitating collaborative modelling efforts that are rapidly validated and summarized.
> I also wonder if we should include this paragraph on the landing page and then add at the end of this paragraph a link to the "who-uses-hubverse" page which has the links out to the different roles.

I think that is a great idea.

2024-08-26 20:16 UTC, zkamvar commented on docs/source/overview/who-uses-hubverse.md
> +Be aware of the needs of everyone above.
:100: will do!

2024-08-26 20:18 UTC, zkamvar commented on docs/source/overview/who-uses-hubverse.md
> +## Decision Makers
Agreed. I couldn't brain that word well when I wrote this.

2024-08-26 20:18 UTC, zkamvar commented on docs/source/overview/who-uses-hubverse.md
> +## Modellers
💯

2024-08-26 20:21 UTC, zkamvar commented on docs/source/overview/who-uses-hubverse.md
> + 2. codifying the submission format for the modelling efforts in `tasks.json`
I'll get it working in the end. I wasn't too concerned with formatting in this push.

2024-08-26 20:40 UTC, zkamvar commented on docs/source/overview/who-uses-hubverse.md
> +# Who is the hubverse For?
I doubled down and went Title Case for everything

2024-08-26 20:41 UTC, zkamvar commented on docs/source/overview/who-uses-hubverse.md
> + 2. codifying the submission format for the modelling efforts in `tasks.json`
Changed this to a nested list (no numbers)

2024-08-26 21:23 UTC, zkamvar commented on docs/source/overview/who-uses-hubverse.md
> +The goal of the hubverse is to **ensure decision makers have model summaries they can trust** by facilitating collaborative modelling efforts that are rapidly validated and summarized.
Done. It will shift as the nature of the landing page changes, but it's a start.

2024-08-26 21:24 UTC, zkamvar commented on docs/source/overview/who-uses-hubverse.md
> +You use R? Great! Python? Go for it! Excel? Nobody's stopping you! Dark Magick? Uh, maybe try a TI-86.
I'm literally going to keep this in here until you tell me to take it out, btw 😝

2024-08-27 15:13 UTC, nickreich requested changes
This all looks great. Several minor comments, but otherwise, I think it's really good.

2024-08-27 15:52 UTC, zkamvar commented on docs/source/overview/who-uses-hubverse.md
> +## Data Analysists
done

2024-08-27 15:52 UTC, zkamvar commented on docs/source/overview/who-uses-hubverse.md
> + - evaluating forecasts
done

2024-08-27 15:52 UTC, zkamvar commented on docs/source/overview/who-uses-hubverse.md
> +We also have a [contributing guide](contribute.md)
done

2024-08-28 13:07 UTC, nickreich approved these changes
Thanks for the responses. LGTM!

2024-08-28 13:07 UTC, merged