Clarify modelling tasks
hubverse-org/hubDocs pull request #173
Opened 2024-09-02 20:56 UTC by zkamvar

This updates the discussion for modelling tasks to put them into a better context. 

I'm trying to clean up some of the language and formatting as well.

2024-09-12 20:03 UTC, bsweger reviewed
Left a few minor wording questions, but these changes are terrific. Every styling decision you've made improves the clarity of the docs 💙

2024-09-12 20:17 UTC, bsweger commented on docs/source/user-guide/tasks.md
> +It has become a convention to use a task ID like `origin_date` or `forecast_date` for this purpose, although this is not a specific restriction.
**Update**: I might be wrong about the YYYY-MM-DD round_id format requirement. We had some discussions about it earlier this year, but I don't remember where we landed and can't really tell from our artifacts:
* https://github.com/orgs/hubverse-org/discussions?discussions_q=round_id
* https://github.com/hubverse-org/hubValidations/discussions/13

2024-09-12 21:52 UTC, zkamvar commented on docs/source/user-guide/tasks.md
> +It has become a convention to use a task ID like `origin_date` or `forecast_date` for this purpose, although this is not a specific restriction.
Oh good point (which also relates to https://github.com/hubverse-org/hubDocs/pull/176#discussion_r1757531803).

The [parsing code in `hubValidations` still expects ISO-8601 dates](https://github.com/hubverse-org/hubValidations/blob/640f68083dc1e5246856bf9d103d838ed17154fc/R/parse_file_name.R#L33-L36) and I don't know that [the discussion in hubValidations](https://github.com/hubverse-org/hubValidations/discussions/13) has been resolved yet.

2024-09-12 21:54 UTC, zkamvar commented on docs/source/user-guide/tasks.md
> +Every Hub is organized around "modeling tasks" that define how the target data should be modelled in terms of
If it's one thing I enjoy, it's repetition, redundancy, and repeating myself.

I say it's definitely worthwhile to include this.

2024-09-12 21:56 UTC, zkamvar commented on docs/source/user-guide/tasks.md
> +It is composed of the following fields:
💀!

2024-09-12 21:57 UTC, zkamvar commented on docs/source/user-guide/tasks.md
> +It is composed of the following fields:
```suggestion
Target metadata comprises the following fields:
```

2024-09-12 22:00 UTC, zkamvar commented on docs/source/user-guide/tasks.md
> +Every Hub is organized around "modeling tasks" that define how the target data should be modelled in terms of
```suggestion
Every Hub is organized around "modeling tasks" that define how the target data (that is, the very thing the hub is trying to predict) should be modeled in terms of 
```

2024-09-19 16:13 UTC, bsweger approved these changes
Thanks again for the great update--I like the "convention" wording used to encourage people to adopt a YYYY-MM-DD string as a round_id!

2024-09-19 20:38 UTC, nickreich requested changes
I love the styling changes - have a few minor requested word-choice/phrasing changes, but nothing major.

2024-09-19 20:38 UTC, nickreich commented on docs/source/user-guide/tasks.md
> +Every Hub is organized around "modeling tasks" that define how the target data (that is, the very thing the hub is trying to predict) should be modeled in terms of
I got a little bit lost in the multiple phases of this sentence, maybe split it up into shorter pieces for more easy readability at the top of this page?

2024-09-19 20:38 UTC, nickreich commented on docs/source/user-guide/tasks.md
> +1. what factors to use for modelling (e.g. date, location, variant, etc) and
"factors" feels to me like not quite the right word here. How about "variables"? I don't love it, but it feels a little bit more specific

2024-09-19 20:38 UTC, nickreich commented on docs/source/user-guide/tasks.md
> +[^json]: Due to technical issues, we do not currently support json references or yaml metadata files.
what does it mean that we don't accept json references?

2024-09-19 20:38 UTC, nickreich commented on docs/source/user-guide/tasks.md
> +Zhian: I am not sure if this 52-word sentence below adds anything.
agree

2024-09-19 20:38 UTC, nickreich commented on docs/source/user-guide/tasks.md
> +* **Allow alignment of model outputs with truth data** by specifying [target data](#target-data) that can help define methods to calculate outputs from "ground truth" data sources.
I think it's confusing here how we talk about "truth data" and "target data". We've been trying to move away from "truth data" as a phrase, although talking about air-quotes "ground truth" is I think a helpful frame of reference. 

Maybe this could just read: 
**Allow alignment of model outputs with [target data](#target-data)** that are derived from "ground truth" data sources.

2024-09-19 20:38 UTC, nickreich commented on docs/source/user-guide/tasks.md
> +* `origin_date`{.codeitem}: the starting point that can be used for calculating a `target_date` via the formula `target_date = origin_date + horizon * time_units_per_horizon` (e.g., with weekly data,
100% agree!

Although I will admit that I am sort of confused/distracted in this section by thinking about why some code is highlighted yellow and other is not. Even the same terms, like "target_date" sometimes is and sometimes isn't.

2024-09-19 20:38 UTC, nickreich commented on docs/source/user-guide/tasks.md
> +```{mermaid}
oooh, pretty. I've never used mermaid before, but it's a nice addition.

2024-09-19 20:38 UTC, nickreich commented on docs/source/user-guide/intro-data-formats.md
> +[^target-key]: Since the target in the simple forecast hub is defined by a
Having this margin-note within the "admonition" section seems to not be working. I can only see part of the note. 
![image](https://github.com/user-attachments/assets/6d20bde1-58e6-4a94-b4f4-5a7fa2d27751)

2024-09-20 13:09 UTC, annakrystalli commented on docs/source/user-guide/tasks.md
> +In general, there are no restrictions on what task ID variables may be named, however when appropriate, we suggest that Hubs adopt the following standard task ID or column names and definitions[^new-
The  main reason we encourage folks to use the naming we've specified alraady (if appropriate) is there is stronger validation of their config via the schema.

2024-09-20 13:45 UTC, zkamvar commented on docs/source/user-guide/intro-data-formats.md
> +[^target-key]: Since the target in the simple forecast hub is defined by a
Yeah, they were misbehaving and I thought I had gotten them to work, but it looks like they continue to misbehave. I'll just add an extra NOTE section in here instead.

2024-09-20 14:10 UTC, annakrystalli submitted a review, later dismissed
Great work! Answered a request for clarification and made some very minor request for removing some superceded info related to previous changes in the schema still lingering here

2024-09-23 17:38 UTC, zkamvar commented on docs/source/user-guide/hub-config.md
>     * Visualization tools may give special treatment to the hub’s ensemble and baseline models, which are identified in the hub configuration files.
fixed in commit e2181a7ea4d5207be7fafb88234f4c3e701fc61e

2024-09-23 17:53 UTC, zkamvar commented on docs/source/user-guide/tasks.md
> +In general, there are no restrictions on what task ID variables may be named, however when appropriate, we suggest that Hubs adopt the following standard task ID or column names and definitions[^new-
I updated this in 76f3f90 to mention the recommended vars first and then indicate that it's possible to add new ones, but with the caveat that they won't have the same validation advantage.

2024-09-23 17:58 UTC, zkamvar commented on docs/source/user-guide/tasks.md
> +[^json]: Due to technical issues, we do not currently support json references or yaml metadata files.
```suggestion
[^json]: Due to technical issues, we do not currently support [json references](http://niem.github.io/json/reference/json-schema/references/) or yaml metadata files.
```

2024-09-25 15:12 UTC, nickreich approved these changes
Thank you again for these great updates!

2024-09-25 15:14 UTC, merged