Adding a "Scripting Task Config" section to the Quickstart guide
hubverse-org/hubDocs pull request #175
Opened 2024-09-10 19:46 UTC by micokoch

Resolving #100 (also [this older one](https://github.com/hubverse-org/hubAdmin/issues/8)) and some other small fixes here and there.

2024-09-10 20:32 UTC, zkamvar requested changes
Thank you for doing this! The content looks great; my comments are mainly cosmetic.

2024-09-10 20:32 UTC, zkamvar commented on docs/source/quickstart-hub-admin/intro.md
> +The [Complex Scenario Hub Example](https://github.com/hubverse-org/example-complex-scenario-hub) is designed to be similar to the [US COVID-19 Scenario Modeling Hub](https://github.com/midas-network/
These are redundant

```suggestion
#### 1. Simple Forecast Hub Example

The [Simple Forecast Hub Example](https://github.com/hubverse-org/example-simple-forecast-hub) is adapted from forecasts submitted to the [US COVID-19 Forecast Hub](https://github.com/reichlab/covid19-forecast-hub), but has been modified to provide examples of nowcasts.  

#### 2. Complex Forecast Hub Example

The [Complex Forecast Hub Example](https://github.com/hubverse-org/example-complex-forecast-hub) is designed to be similar to the [US COVID-19 Forecast Hub](https://github.com/reichlab/covid19-forecast-hub) and the [European COVID-19 Forecast Hub](https://github.com/covid19-forecast-hub-europe/covid19-forecast-hub-europe).  

#### 3. Complex Scenario Hub Example

The [Complex Scenario Hub Example](https://github.com/hubverse-org/example-complex-scenario-hub) is designed to be similar to the [US COVID-19 Scenario Modeling Hub](https://github.com/midas-network/covid19-scenario-modeling-hub)  
```

2024-09-10 20:32 UTC, zkamvar commented on docs/source/quickstart-hub-admin/intro.md
> +The main benefit of setting up a hub using the structure outlined in this documentation is that it enables you to use a wide array of tools designed to support common modeling hub tasks, like loading
```suggestion
### Software for modeling hubs 

The main benefit of setting up a hub using the structure outlined in this documentation is that it enables you to use a wide array of [tools designed to support common modeling hub tasks](../user-guide/software.md), like loading model output data, plotting the model output data, building ensembles using the data, and in some cases evaluating the predictions made by different models.  
```

2024-09-10 20:32 UTC, zkamvar commented on docs/source/quickstart-hub-admin/scripting-task-config.md
> +The [`hubAdmin` package](https://hubverse-org.github.io/hubAdmin/index.html) provides tools to help with the configuration of [tasks](../user-guide/tasks.md) that are run on the hub. Specifically, th
```suggestion
The [`hubAdmin` package](https://hubverse-org.github.io/hubAdmin/index.html) provides tools to help with the [configuration of tasks](../user-guide/tasks.md) that are run on the hub. Specifically, the package has various [`create` functions](https://hubverse-org.github.io/hubAdmin/reference/index.html) that can be used to create objects that are used to build a [`"tasks"` config file](https://hubverse-org.github.io/hubAdmin/reference/create_config.html) that can ultimately be written as a [`tasks.json` file](#model-tasks-schema).  
```

2024-09-10 20:32 UTC, zkamvar commented on docs/source/quickstart-hub-admin/scripting-task-config.md
> +:alt: Screenshot for creating a new folder in RStudio called "src"
```suggestion
:alt: Screenshot for creating a new folder in RStudio called "src", as described in text.
```

2024-09-10 20:32 UTC, zkamvar commented on docs/source/quickstart-hub-admin/scripting-task-config.md
> +:alt: Screenshot for creating a new R Script called "scripting-task-config" in the "src" folder
```suggestion
:alt: Screenshot for creating a new R Script called "scripting-task-config" in the "src" folder, as described in text.
```

2024-09-10 20:32 UTC, zkamvar commented on docs/source/quickstart-hub-admin/scripting-task-config.md
> +:alt: Screenshot showing command for installing hubAdmin package
```suggestion
:alt: Screenshot showing command for installing hubAdmin package, as described in text.
```

2024-09-10 20:32 UTC, zkamvar commented on docs/source/quickstart-hub-admin/scripting-task-config.md
> +```
Make the indentations consistent and use the `write_config()` function from hubAdmin.

````suggestion
``` r
# Load the hubAdmin package
library(hubAdmin)

# Create a representation of a task ID item as a list object of `class task_id`, the `origin_date_id`
origin_date_id <- create_task_id(
  "origin_date", 
  required = NULL, 
  optional = c("2023-01-02", "2023-01-09", "2023-01-16")
)

# Create a representation of a task ID item as a list object of `class task_id`, the `location_id`
location_id <- create_task_id(
  "location",
  required = "US",
  optional = c("01", "02", "04", "05", "06")
)

# Create a representation of a task ID item as a list object of `class task_id`, the `horizon_id`
horizon_id <- create_task_id("horizon", required = 1L, optional = 2:4)

# Create a representation of a task ID item as a list object of `class task_id`, the `target_id`
target_id <- create_task_id("target", required = "inc hosp", optional = "inc death")

# Combine the `task_id` objects to create a `task_ids` class object, the `task_ids_example`
task_ids_example <- create_task_ids(origin_date_id, location_id, horizon_id, target_id)

```

### 4.2. Creating the `output_type` objects  
Write or copy the lines of code written below after the `task_id` objects in your `scripting-task-config.R` file.  

``` r
# Create a representation of a `mean` output type as a list object of class `output_type_item`
mean_example <- create_output_type_mean(
  is_required = TRUE, 
  value_type = "double", 
  value_minimum = 0L
)

# Create a representation of a `median` output type as a list object of class `output_type_item`
median_example <- create_output_type_median(is_required = FALSE, value_type = "integer")

# Create a representation of a `quantile` output type as a list object of class `output_type_item`
quantile_example <- create_output_type_quantile(
  required = c(0.25, 0.5, 0.75), 
  optional = c(0.1, 0.2, 0.3, 0.4, 0.6, 0.7, 0.8, 0.9), 
  value_type = "double", 
  value_minimum = 0
)

# Combine the point estimate `output_type_item` objects to create an `output_type` class object, the `output_type_example1`
output_type_example1 <-  create_output_type(mean_example, median_example)

# Combine the other `output_type_item` objects to create an `output_type` class object, the `output_type_example2`
output_type_example2 <- create_output_type(mean_example, quantile_example)
```

### 4.3. Creating the `target_metadata` objects  
Write or copy the lines of code written below after the `output_type` objects in your `scripting-task-config.R` file.  

``` r
# Create a representation of a `target_metadata` item as a list object of class `target_metadata_item`, the `target_metadata_item1` that will hold the metadata for the target of incident influenza hospitalizations
target_metadata_item1 <- create_target_metadata_item(
  target_id = "inc hosp", 
  target_name = "Weekly incident influenza hospitalizations", 
  target_units = "rate per 100,000 population", 
  target_keys = list(target = "inc hosp"), 
  target_type = "discrete", 
  is_step_ahead = TRUE, 
  time_unit = "week"
)

# Create a representation of a `target_metadata` item as a list object of class `target_metadata_item`, the `target_metadata_item2`, that will hold the metadata for the target of incident influenza deaths
target_metadata_item2 <- create_target_metadata_item(
  target_id = "inc death", 
  target_name = "Weekly incident influenza deaths", 
  target_units = "rate per 100,000 population", 
  target_keys = list(target = "inc death"), 
  target_type = "discrete", 
  is_step_ahead = TRUE, 
  time_unit = "week"
)

# Combine the `target_metadata_item` objects to create a `target_metadata` class object, the `target_metadata_example`
target_metadata_example <- create_target_metadata(target_metadata_item1, target_metadata_item2)
```

### 4.4. Creating the `model_task` objects  
Write or copy the lines of code written below after the `target_metadata` objects in your `scripting-task-config.R` file.  

``` r
#Create an object of class `model_task` representing a model task, the `model_task_item1`
model_task_item1 <- create_model_task(
  task_ids = task_ids_example, 
  output_type = output_type_example1, 
  target_metadata = target_metadata_example
)

#Create another object of class `model_task` representing a similar model task, the `model_task_item2`
model_task_item2 <- create_model_task(
  task_ids = task_ids_example, 
  output_type = output_type_example2, 
  target_metadata = target_metadata_example
)

# Combine the `model_task` objects to create a `model_tasks` class object, the `model_task_example`
model_task_example <- create_model_tasks(model_task_item1, model_task_item2)
```

### 4.5. Creating the `round` objects  
Write or copy the lines of code written below after the `model_task` objects in your `scripting-task-config.R` file.  

``` r
# Create a representation of a round as a list object of class `round`, the `round1`
round1 <- create_round(
  round_id_from_variable = TRUE,
  round_id = "origin_date",
  round_name = "Round 1",
  model_tasks = model_task_example,
  submissions_due = list(
    relative_to = "origin_date",
    start = -4L,
    end = 2L
  )
)

# Create a different representation of a round as a list object of class `round`, the `round2`
round2 <- create_round(
  round_id_from_variable = TRUE,
  round_id = "origin_date",
  round_name = "Round 2",
  model_tasks = model_task_example,
  submissions_due = list(start = "2023-01-09", end = "2023-01-16")
)

# Combine the `round` objects to create a `rounds` class object, the `rounds`
rounds <- create_rounds(round1, round2)
```

### 4.6. Creating and saving the `tasks` config file
Write or copy the lines of code written below after the `round` objects in your `scripting-task-config.R` file.  

``` r
# Create a representation of a complete `"tasks"` config file as a list object of class `config`
config <- create_config(rounds)

# Write the `config` object to a JSON file (note that this will overwrite any existing file with the same name in the "hub-config" folder)
write_config(config, hub_path = ".")
```
````

2024-09-10 20:32 UTC, zkamvar commented on docs/source/quickstart-hub-admin/setting-up.md
>  - The contact person is: S Brown (sbrown@xxx.com)
Best practice for example sites/emails is example.com

```suggestion
- The contact person is: S Brown (`sbrown@example.com`)  
```

2024-09-11 18:43 UTC, micokoch commented
@zkamvar - I accepted all the changes you requested and made one small fix on your write_config() code because if someone were following the Quickstart Guide, they should already have a `tasks.json` file. If approved, this is ready to merge.

2024-09-11 21:25 UTC, zkamvar approved these changes

2024-09-11 21:25 UTC, merged