initial cleanup of model-output
hubverse-org/hubDocs pull request #176
Opened 2024-09-10 19:48 UTC by zkamvar

2024-09-12 20:41 UTC, bsweger reviewed
Left a few minor questions, but once again, a vast improvement--thank you!

2024-09-12 20:41 UTC, bsweger commented on docs/source/user-guide/model-output.md
> +:::{table} An example of a model output submission for modelA
Love the example table here (as long as we're sure that round_id doesn't need to be in YYYY-MM-DD format, which I continue to be confused about)

2024-09-12 20:41 UTC, bsweger commented on docs/source/user-guide/model-output.md
> +Model output data are stored as separate files, but we use the `hubData` package to open them as a single [arrow dataset](https://arrow.apache.org/docs/r/reference/Dataset.html).
Not sure if it's worth including here, but even people who don't plan to use `hubData` to interact with model output files will have trouble if the parquet files have different schemas.

_I.e._, uniform schemas aren't only necessary to work with hubverse tools, they're necessary for any parquet-based hub if users want to join model-output files and do analysis across submissions.

2024-09-12 20:41 UTC, bsweger commented on docs/source/user-guide/model-output.md
> + - an inability to open hub model output data as an `arrow` dataset
What if we word this last point to make it clear that `arrow` won't be the only tool impacted by mis-matched parquet schemas?

Something like: 
`- errors when opening hub model output data with popular analytics tools like arrow, pandas, and polars`
?

2024-09-12 21:35 UTC, zkamvar commented on docs/source/user-guide/model-output.md
> +:::{table} An example of a model output submission for modelA
Thank you! This was lifted directly from further down in the document... I just realized that it would have helped me a lot to see what these tables actually looked like before going into the weeds of what the columns could be.

2024-09-12 21:36 UTC, zkamvar commented on docs/source/user-guide/model-output.md
> +Model output data are stored as separate files, but we use the `hubData` package to open them as a single [arrow dataset](https://arrow.apache.org/docs/r/reference/Dataset.html).
It probably is worth adding here in some fashion. I'll add it.

2024-09-12 21:36 UTC, zkamvar commented on docs/source/user-guide/model-output.md
> + - an inability to open hub model output data as an `arrow` dataset
Definitely a good add.

2024-09-12 21:43 UTC, zkamvar commented on docs/source/user-guide/model-output.md
> +:::{table} An example of a model output submission for modelA
And I just checked in the schema, it _does not_ need to be in ISO-8601 format.

2024-09-12 21:49 UTC, zkamvar commented on docs/source/user-guide/model-output.md
> +:::{table} An example of a model output submission for modelA
Oh-ho! https://github.com/hubverse-org/hubValidations/discussions/13

2024-09-19 16:19 UTC, bsweger commented on docs/source/user-guide/model-output.md
> +:::{table} An example of a model output submission for modelA
> Oh-ho! [hubverse-org/hubValidations#13](https://github.com/hubverse-org/hubValidations/discussions/13)

I still don't understand where we landed on the YYYY-MM-DD thing. If it's still the case that our tooling expects YYYY-MM-DD, I'd propose that the model output file example use a reference date, origin date, or something else that can expressed in that format.

2024-09-19 20:49 UTC, nickreich requested changes
A few minor requested changes, but overall these changes look great and improve the readability.

2024-09-19 20:49 UTC, nickreich commented on docs/source/user-guide/model-output.md
> +:::{table} An example of a model output submission for modelA
I think we do expect any dates to be in YYYY-MM-DD format.

I think round IDs could in theory be something that are not dates. Would be nice to have @annakrystalli confirm.

2024-09-19 20:49 UTC, nickreich commented on docs/source/user-guide/model-output.md
> +[^Shandross-etal]: Shandross, L., Howerton, E., Contamin, L., Hochheiser, H., Krystalli, A., Consortium of Infectious Disease Modeling Hubs, Reich, N. G., Ray, E.L. (2024). [hubEnsembles: Ensembling
Could we have two links here:
1. preprint paper: https://www.medrxiv.org/content/10.1101/2024.06.24.24309416v1
2. the existing link to the github repo?

2024-09-19 20:49 UTC, nickreich commented on docs/source/user-guide/model-output.md
> +[^troube]: Even if you do not use `hubData` to read model outputs, uniform schemas are still important if you want to join model output files and do analyses across submissions.
this should be "trouble" currently it is "troube"

2024-09-20 13:28 UTC, annakrystalli commented on docs/source/user-guide/model-output.md
> +:::{table} An example of a model output submission for modelA
Yup, currently `round_id`s can consist of alphanumerics and underscores or ISO dates

2024-09-20 13:59 UTC, zkamvar commented on docs/source/user-guide/model-output.md
> +[^Shandross-etal]: Shandross, L., Howerton, E., Contamin, L., Hochheiser, H., Krystalli, A., Consortium of Infectious Disease Modeling Hubs, Reich, N. G., Ray, E.L. (2024). [hubEnsembles: Ensembling
Absolutely!


```suggestion
[^Shandross-etal]: Shandross, L., Howerton, E., Contamin, L., Hochheiser, H., Krystalli, A., Consortium of Infectious Disease Modeling Hubs, Reich, N. G., Ray, E.L. (2024). [hubEnsembles: Ensembling Methods in R](https://www.medrxiv.org/content/10.1101/2024.06.24.24309416v1). *(under review for publication)* (Repo: https://github.com/hubverse-org/hubEnsemblesManuscript).
```

2024-09-20 14:01 UTC, zkamvar commented on docs/source/user-guide/model-output.md
> +[^troube]: Even if you do not use `hubData` to read model outputs, uniform schemas are still important if you want to join model output files and do analyses across submissions.
So, what you're telling me is that you are... 


.... looking for trouble ^_^

```suggestion
[^trouble]: Even if you do not use `hubData` to read model outputs, uniform schemas are still important if you want to join model output files and do analyses across submissions.
```

(good catch!)

2024-09-20 14:08 UTC, annakrystalli requested changes
Great start! Added some clarifications + suggestions

2024-09-20 14:08 UTC, annakrystalli commented on docs/source/user-guide/model-output.md
> + - [arrow schema](https://arrow.apache.org/docs/11.0/r/reference/Schema.html)---the schema for **model output columns in parquet files**.
```suggestion
 - [arrow schema](https://arrow.apache.org/docs/11.0/r/reference/Schema.html)---the mapping of model output columns to arrow data types.
```

This does not only involve parquet files. It also refers to the schema created when opening a hub data set using arrow so the original description is more accurate.

2024-09-20 14:08 UTC, annakrystalli commented on docs/source/user-guide/model-output.md
> +When we know that all data types conform to the arrow schema, we can be sure that a hub can be [successfully accessed and fully queryable across all columns as an arrow dataset](https://arrow.apache.
```suggestion
When we know that all data types conform to the arrow schema, we can be sure that a hub can be [successfully accessed and is fully queryable across all columns as an arrow dataset](https://arrow.apache.org/docs/r/articles/dataset.html)
```

2024-09-20 14:08 UTC, annakrystalli commented on docs/source/user-guide/model-output.md
> +However, there are a number of situations where a single consistent data type cannot be guaranteed, e.g.:
I actually prefer the original here because it mentions why they are validated and stable (i.e. because they are covered by the schema)

2024-09-20 14:08 UTC, annakrystalli commented on docs/source/user-guide/model-output.md
> +However, there are a number of situations where a single consistent data type cannot be guaranteed, e.g.:
Also model outputs are not validated during hub configuration but during file submission so this is a bit confusing as is

2024-09-20 14:08 UTC, annakrystalli commented on docs/source/user-guide/model-output.md
> +Some examples of issues caused by a change in the overal data type of model output columns:
Again I prefer the original because the description as a range confers the change in severity whereas this is somewhat lost by the bullets

2024-09-23 15:06 UTC, zkamvar commented on docs/source/user-guide/model-output.md
> +Per hubverse convention, **there are three groups of columns**, each group serving a specific purpose: (1) the **"model ID"** is a single column that denotes which model has produced the prediction,
Oh this is a very good point and it gets at the whole "personas" aspect.

I might put a side comment about the `model ID` aspect since that's only relevant for people who are consuming the data (admins and analysts)

2024-09-23 15:09 UTC, zkamvar commented on docs/source/user-guide/model-output.md
> +      these columns will be used by all Hubs:
Oh good catch! Definitely a subtle but important distinction.

2024-09-23 15:17 UTC, zkamvar commented on docs/source/user-guide/model-output.md
> +The following table provides examples that better explain how the "model output representation" columns are used:
I agree that the original sentence is vague, but I wonder if this might hit the mark better:  

```suggestion
The following table provides more detail on how to configure the three "model output representation" columns based on the type of prediction used. 
```

2024-09-23 15:24 UTC, zkamvar commented on docs/source/user-guide/model-output.md
>  ## Validating forecast values
I'm going to make the executive decision to update this to "prediction" since we use that term earlier in the document.

2024-09-23 15:36 UTC, zkamvar commented on docs/source/user-guide/model-output.md
> +Validation of forecast submissions is done with the function
```suggestion
Before model outputs can be incorporated into a hub, they must be validated. If a hub is centrally stored on GitHub, validations checks will be automatically performed for each submission (via the [`validate_pr()` function](https://hubverse-org.github.io/hubValidations/reference/validate_submission.html) from the `hubValidations` R package).  

Validation of submissions is done with the function 
```

2024-09-23 15:42 UTC, zkamvar commented on docs/source/user-guide/model-output.md
> +      within each model task, up to some specified tolerance.
```suggestion
* Validation of more involved rules that cannot be encoded in a json schema are
  implemented separately (such as specific relationships between outputs and
  targets). You can a table with the details of each check in [the `validate_submission()` documentation](https://hubverse-org.github.io/hubValidations/reference/validate_submission.html#details) and [the `validate_pr()` documentation](https://hubverse-org.github.io/hubValidations/reference/validate_pr.html#details).
```

2024-09-23 15:43 UTC, zkamvar commented on docs/source/user-guide/model-output.md
> +      within each model task, up to some specified tolerance.
I agree. It seemed weird to bring up just a couple of things that were checked, but not give a complete list. Your solution is much better!

2024-09-23 15:43 UTC, zkamvar commented on docs/source/user-guide/model-output.md
> +      within each model task, up to some specified tolerance.
see https://github.com/hubverse-org/hubDocs/pull/176/files#r1771696626

2024-09-23 15:45 UTC, zkamvar commented on docs/source/user-guide/model-output.md
> +:::{table} An example of a model output submission for modelA
I will resolve this as the statement has not deviated from the original description.  When we make a decision to change it, an issue should be opened and we will address it there.

2024-09-23 16:14 UTC, zkamvar commented on docs/source/user-guide/model-output.md
> +However, there are a number of situations where a single consistent data type cannot be guaranteed, e.g.:
I think when I was initially reading this, I was confused by the sentence structure (many W are X, are Y and should Z). I've modified the sentence in https://github.com/hubverse-org/hubDocs/pull/176/files#r1771741223

2024-09-23 16:30 UTC, zkamvar commented on docs/source/user-guide/model-output.md
> +Some examples of issues caused by a change in the overal data type of model output columns:
I didn't really understand "These issues can range from" as a range of severity, per se. It just seemed like a range of examples. The only thing that was changed was to move the two sentences of examples to a list. I think this can restore the meaning of the change in severity: 

```suggestion
Changing the overall data type of model output columns can cause a range of issues (in order of _increasing severity_):
```

2024-09-24 13:57 UTC, annakrystalli commented on docs/source/user-guide/model-output.md
> +The following table provides examples that better explain how the "model output representation" columns are used:
Mainly fine. I think it's good to stick to the standard name of "output type" not "type of prediction" for clarity. Honestly I feel my proposal was clearer but I'm not too fussed.

2024-09-24 13:58 UTC, annakrystalli commented on docs/source/user-guide/model-output.md
> +Some examples of issues caused by a change in the overal data type of model output columns:
All good!

2024-09-24 14:00 UTC, annakrystalli commented
Thanks for all the edits! I've added one minor comment but it's certainly not a blocker so will approve from my end!

2024-09-24 14:00 UTC, annakrystalli approved these changes

2024-09-24 15:43 UTC, merged