Add mention of "model_output_dir" key in documentation; fix broken crossrefs
hubverse-org/hubDocs pull request #188
Opened 2024-10-02 20:05 UTC by zkamvar

This adds a sidetone about "model_output_dir" in two places that mention `model-output` to fix #187 

Requesting a review from @mmkerr because she's working on the manuscript and I want to make sure this is accurate.

Also requesting a review from @matthewcornell who requested the change and @annakrystalli who knows the most about this specification.

2024-10-02 21:26 UTC, matthewcornell approved these changes
This looks good to me, though I'm not sure how to rigorously check the updated markdown links without a preview. Thanks!

2024-10-02 22:57 UTC, zkamvar commented
> This looks good to me, though I'm not sure how to rigorously check the updated markdown links without a preview. Thanks!

Luckily RTD checks the crosslinks automatically (they were broken earlier because I was not familiar with the system and assumed that it was always just screaming at me about something trivial).

The markdown preview is always going to be under the information from the checks in this repo. Here's the link: https://hubdocs--188.org.readthedocs.build/en/188/

2024-10-03 13:30 UTC, mmkerr approved these changes
Hi @Zhian, this looks good to me. I must admit I haven't gotten into this much detail in the manuscript, but this is good to know.

2024-10-03 13:42 UTC, annakrystalli requested changes

2024-10-03 13:42 UTC, annakrystalli commented on docs/source/user-guide/hub-structure.md
> +  use a custom directory path by setting the `"model_output_dir"` key in the
We generally call JSON fields **properties** instead of keys throughout docs so probably best to stick to that to avoid confusion.

2024-10-03 13:43 UTC, annakrystalli commented
One very minor naming change requested for consistency throughout docs but overall looks great! Thanks @zkamvar !

2024-10-03 13:52 UTC, zkamvar commented on docs/source/user-guide/hub-structure.md
> +  use a custom directory path by setting the `"model_output_dir"` key in the
💯 for squashing fluid representations!

2024-10-03 13:53 UTC, zkamvar commented on docs/source/user-guide/hub-structure.md
> +  use a custom directory path by setting the `"model_output_dir"` key in the
```suggestion
  use a custom directory path by setting the `"model_output_dir"` property in the
```

2024-10-03 13:53 UTC, zkamvar commented on docs/source/user-guide/model-output.md
> +    use a custom directory path by setting the `"model_output_dir"` key in the
```suggestion
    use a custom directory path by setting the `"model_output_dir"` property in the
```

2024-10-08 15:47 UTC, merged