Quickstart uninformative links and Grammarly edits
hubverse-org/hubDocs pull request #189
Opened 2024-10-08 23:22 UTC by micokoch

Partially addresses #166 and some Friction log items (#152).

2024-10-09 22:38 UTC, zkamvar requested changes
Thank you! This looks good so far. I have some suggestions that are detailed below.

Getting rid of the uninformative link text when there is so much of it is really not easy. It's so much easier to come up with on the fly. I really appreciated you clobbering not only those, but also the repetitive links that just went to the same place.

2024-10-09 22:38 UTC, zkamvar commented on docs/source/quickstart-hub-admin/continuous-integration.md
> +This hubverse action installs the `hubValidations` package from GitHub using [pak](https://pak.r-lib.org/) and the required system dependencies.
I think this sentence overall needed clarification. 

```suggestion
This hubverse action installs the `hubValidations` package and the required system dependencies using [pak](https://pak.r-lib.org/).
```

Last month, we updated the workflows to install the packages from the r-universe, not GitHub.

2024-10-09 22:38 UTC, zkamvar commented on docs/source/quickstart-hub-admin/continuous-integration.md
> +More information can be found on [the `validate-submission` GitHub page](https://github.com/hubverse-org/hubverse-actions/tree/main/validate-submission) and in the hubValidations vignette on [Validat
```suggestion
More information can be found on [the `validate-submission` README](https://github.com/hubverse-org/hubverse-actions/tree/main/validate-submission#readme) and in the hubValidations vignette on [Validating Pull Requests on GitHub](https://hubverse-org.github.io/hubValidations/articles/validate-pr.html).
```

2024-10-09 22:38 UTC, zkamvar commented on docs/source/quickstart-hub-admin/continuous-integration.md
> +This action uploads your hub data to hubverse hosted cloud storage. Currently, the workflow has a single job, `upload`, that pushes data to an Amazon Web Services (AWS) Simple Storage Service (S3) bu
the hyphen stays. 

```suggestion
This action uploads your hub data to hubverse-hosted cloud storage. Currently, the workflow has a single job, `upload`, that pushes data to an Amazon Web Services (AWS) Simple Storage Service (S3) bucket.
```

2024-10-09 22:38 UTC, zkamvar commented on docs/source/quickstart-hub-admin/continuous-integration.md
> +* uses `cloud.host.storage` to determine the name of the hub's S3 bucket and
In this case, the item above should also have a comma at the end.

2024-10-09 22:38 UTC, zkamvar commented on docs/source/quickstart-hub-admin/continuous-integration.md
> +More information can be found on [the `hubverse-aws-upload` GitHub page](https://github.com/hubverse-org/hubverse-actions/tree/main/hubverse-aws-upload).
```suggestion
More information can be found on [the `hubverse-aws-upload` README](https://github.com/hubverse-org/hubverse-actions/tree/main/hubverse-aws-upload#readme).  
```

2024-10-09 22:38 UTC, zkamvar commented on docs/source/quickstart-hub-admin/getting-started.md
> +You can go ahead and move on to the next step if you already have a GitHub account.  If you do not have a GitHub account, [follow these instructions to create a GitHub account](https://docs.github.co
I think the original step was better because it tells people to do the action after they confirmed that they already have the account. 

```suggestion
_If you already have a GitHub account, you can move on to the next step._ If you do not have a GitHub account, [follow these instructions to create a GitHub account](https://docs.github.com/en/get-started/signing-up-for-github/signing-up-for-a-new-github-account) (a free account is fine).  
```

2024-10-09 22:38 UTC, zkamvar commented on docs/source/quickstart-hub-admin/getting-started.md
> +Enter a name for your repository—you can use any name.  Then click on "Create repository".
Three hyphens will make an em-dash, which is clearly distinguishable in code. 

```suggestion
Enter a name for your repository---you can use any name.  Then click on "Create repository".  
```

2024-10-09 22:38 UTC, zkamvar commented on docs/source/quickstart-hub-admin/model-metadata-schema.md
> +For each model that is submitted to the hub, a yaml metadata file ([what is a yaml file?](https://circleci.com/blog/what-is-yaml-a-beginner-s-guide/)) must be added to the `model-metadata` directory
```suggestion
For each model that is submitted to the hub, a yaml metadata file ([what is a yaml file?](https://circleci.com/blog/what-is-yaml-a-beginner-s-guide/)) must be added to the `model-metadata` directory by the modeling teams. Details about the `model-metadata` directory can be found in [the model metadata chapter](../user-guide/model-metadata.md).  
```

2024-10-09 22:38 UTC, zkamvar commented on docs/source/quickstart-hub-admin/tasks-config.md
> +Every Hub is organized around "modeling tasks" that are defined to meet the needs of a project. Modeling tasks are defined for a hub in the [`tasks.json` file](#model-tasks-schema), which specifies t
```suggestion
Every Hub is organized around "modeling tasks" that are defined to meet the needs of a project. Modeling tasks are defined for a hub in the [`tasks.json` file](#model-tasks-schema), which specifies the three components of modeling tasks ([task ID variables](#task-id-vars), [output types](#output-types), and [target metadata](#target-metadata)). You can read a detailed definition of modeling tasks [in the "Defining Modeling Tasks" chapter](../user-guide/tasks.md).  
```

2024-10-09 22:38 UTC, zkamvar commented on docs/source/quickstart-hub-admin/tasks-config.md
> +You should see the code below in your source panel (upper left-hand panel). [Each line of code in `tasks.json`](#model-tasks-schema) is detailed in the link.
I think this sentence needed some clarification in the first place. 

```suggestion
You should see the code below in your source panel (upper left-hand panel). This has a specific structure and you can explore that [in the interactive `tasks.json` schema explorer](#model-tasks-schema)  
```

2024-10-09 22:38 UTC, zkamvar commented on docs/source/quickstart-hub-admin/tasks-config.md
> +Open `tasks.json` and explore the content and structure. Simple explanations for elements in the Example Forecast Hub file are offered below (*click on the hyperlinks for a full explanation of all th
Oof. That was outdated. 

```suggestion
Open `tasks.json` and explore the content and structure. Simple explanations for elements in the Example Forecast Hub file are offered below (*click on the hyperlinks for a full explanation of all the supported elements in [a `tasks.json` file](#model-tasks-schema) and definitions of [key concepts](../overview/definitions.md)*):  
```

2024-10-09 22:38 UTC, zkamvar commented on docs/source/quickstart-hub-admin/tasks-config.md
> +Click on the link to read more on [how to use `target_date` and `target_end_date`](https://raw.githubusercontent.com/hubverse-org/schemas/main/v2.0.1/tasks-schema.json#L400).
I'm tempted to just remove this because this has been an outdated link for a while. 

```suggestion
```

2024-10-09 22:38 UTC, zkamvar commented on docs/source/quickstart-hub-admin/tasks-config.md
> +[The schema permits two ways](https://github.com/hubverse-org/schemas/blob/de580d56b8fc5c24dd36a32994182e37b8b0ac95/v2.0.0/tasks-schema.json#L1323-L1380) to set the dates during which model forecasts
```suggestion
The schema permits two ways to set the dates during which model forecasts can be submitted:  
```

2024-10-09 22:38 UTC, zkamvar commented on docs/source/quickstart-hub-admin/uploading-validating.md
> +1. First, you must install the R package `hubAdmin`. Click on the link for [instructions for installing `hubAdmin` in the R console](https://github.com/hubverse-org/hubAdmin#installation).
```suggestion
1. First, you must [follow the instructions to install the R package `hubAdmin` in the R console](https://github.com/hubverse-org/hubAdmin#installation).  
```

2024-10-09 22:38 UTC, zkamvar commented on docs/source/quickstart-hub-admin/uploading-validating.md
> +- [`validate_config()`](https://hubverse-org.github.io/hubAdmin/reference/validate_config.html) validates a single hub config file against its corresponding schema.
This was confusing to me when I started because `validate_hub_config()` actually calls `validate_config()`. I think it would be better to just leave it out. The documentation explains what's happening. 

```suggestion
```

2024-10-09 22:38 UTC, zkamvar commented on docs/source/quickstart-hub-admin/uploading-validating.md
> +- Click on the link for more [detailed instructions and explanations](https://hubverse-org.github.io/hubAdmin/articles/hub-setup.html#validate-config-files).
```suggestion
- More detailed explanations can be found in [hubAdmin's "Setting Up a Hub" vignette](https://hubverse-org.github.io/hubAdmin/articles/hub-setup.html#validate-config-files).
```

2024-10-09 22:38 UTC, zkamvar commented on docs/source/quickstart-hub-admin/using-hub.md
> +Many hubs will focus on modeling tasks where the goal is to estimate or predict a quantity that is, in principle, observable. We refer to this as 'target data'. Click on the link to read [a detailed
```suggestion
Many hubs will focus on modeling tasks where the goal is to estimate or predict a quantity that is, in principle, observable. We refer to this as 'target data', which is detailed in the [Target Data chapter](../user-guide/target-data.md).  
```

2024-10-10 12:26 UTC, micokoch commented
Thanks for carefully reviewing this, @zkamvar. I accepted and implemented all your suggestions. If you approve, this should be ready to merge.

2024-10-10 14:15 UTC, zkamvar approved these changes
Thank you!

2024-10-10 14:15 UTC, merged