addressing #201
hubverse-org/hubDocs pull request #202
Opened 2024-10-23 15:47 UTC by micokoch

Addressing issue #201

2024-10-23 18:48 UTC, zkamvar commented
Ah crap. This was part of my changes in #197 🙈

2024-10-23 20:15 UTC, LucieContamin approved these changes
Looks good to me! thanks!

2024-10-24 15:30 UTC, zkamvar requested changes
One more change from my previous review that I cannot suggest on the PR itself: 

line 81 needs to be changed to reflect that the model output representation is made up of two columns and is followed by the model output value column.

2024-10-24 15:44 UTC, micokoch commented
Hi @zkamvar ! Thanks for looking at the page more carefully. I accepted the changes you suggested and edited line 81. I hope that works for you.

2024-10-24 16:06 UTC, zkamvar requested changes
Looks good! One more change for clarity.

2024-10-24 16:06 UTC, zkamvar commented on docs/source/user-guide/model-output.md
> +Per hubverse convention, **there are two groups of columns and one column for model output**[^model-id]. Each group of columns serves a specific purpose: (1) the **"task ID"** columns provide details
```suggestion
Per hubverse convention, **there are two groups of columns for model output**[^model-id] followed by a single column for values. Each group of columns serves a specific purpose: (1) the **"task ID"** columns provide details about what is being predicted, and (2) the two **"model output representation"** columns specify the type of prediction and identifying information about that prediction. Finally, (3) the **value** column provides the model output of the prediction.  
```

2024-10-24 16:23 UTC, micokoch commented on docs/source/user-guide/model-output.md
> +Per hubverse convention, **there are two groups of columns and one column for model output**[^model-id]. Each group of columns serves a specific purpose: (1) the **"task ID"** columns provide details
From my understanding of #201, the column for model output is the column for values (the others are "metadata about the representation of that output"). I phrased it differently in my most recent commit.

2024-10-24 16:56 UTC, zkamvar approved these changes
LGTM! Thank you for your patience!

2024-10-24 17:46 UTC, merged