add Evan's writeup, lightly edited
hubverse-org/hubDocs pull request #208
Opened 2024-11-06 22:56 UTC by zkamvar

2024-11-14 19:55 UTC, LucieContamin reviewed
Looking good! thank you very much. I just made some comments mainly minor suggestions to re-organize or add more information.

2024-11-14 19:55 UTC, LucieContamin commented on docs/source/user-guide/target-data.md
> +hubs that collect pmf or cdf predictions, the formats will differ more
Should we add one or two sentences to indicate more information below if available and link it to you? 
Or reorganize the file to have the "more about" directly after?

2024-11-14 19:55 UTC, LucieContamin commented on docs/source/user-guide/target-data.md
> +
Should we add recommendation on where to store the data? For example in a `target-data` folder?

2024-11-14 19:55 UTC, LucieContamin commented on docs/source/user-guide/target-data.md
> +### Oracle output vs model output
Should we put the information a little bit higher, I think it helps a lot with understanding why we design it that way. For example, at the beginning of the "Oracle output" section.

2024-11-14 19:55 UTC, LucieContamin commented on docs/source/user-guide/target-data.md
> +**The oracle output will contain the independent task ID variables** that are
Do you mean "independent and any other variables" necessary to match?
Because you will need some date/time information probably and with this list, it seems that all time related variable are called "derived".

2024-11-14 20:32 UTC, zkamvar commented on docs/source/user-guide/target-data.md
> +  with the corresponding predicted `value`s produced by modelers.
Good catch! Thank you!

2024-11-14 20:35 UTC, zkamvar commented on docs/source/user-guide/target-data.md
> +
Yes! Thank you for mentioning this! In fact, we should have recommendations for standardized file names (unless we want to have a way to specify this in the admin schema).

2024-11-14 20:38 UTC, zkamvar commented on docs/source/user-guide/target-data.md
> +### Oracle output vs model output
I think that's a good point. I'll move it up.

2024-11-14 20:52 UTC, zkamvar commented on docs/source/user-guide/target-data.md
> +**The oracle output will contain the independent task ID variables** that are
Probably. I was trying to avoid over-complicating the statement. Thinking about it, the oracle data should have the same columns as the time series data (except `date` is renamed to `target_date`) with additional columns that describes the metadata about the outputs.... unless I'm completely off-base? 

I was attempting to summarize @elray1's original text:

>  - The oracle output should include enough of the task id variables and columns with metadata about the outputs (output_type and output_type_id) to uniquely identify which oracle_values correspond to which predicted values. For example, this will typically include task id variables such as location and target_date (or target_end_date), since the oracle_value will be specific to the location and target_date.
>  - Any task id variables that are not necessary to match observations with predictions can be omitted from the oracle output. For example, if target_date is included then reference_date and horizon variables can be omitted because the same observation will generally correspond to a particular target_date regardless of the forecast horizon. Similarly, in a scenario projection setting, the scenario_id can be omitted.

2024-11-14 22:06 UTC, zkamvar commented on docs/source/user-guide/target-data.md
> +hubs that collect pmf or cdf predictions, the formats will differ more
Agreed this is a bit hedging, so I've moved it before the description of the column types so that it flows better.

2024-11-14 22:18 UTC, zkamvar commented
In thinking about this, I realize that there are still gaps in defining the standard for time series data. We mention that it should be in long format (albeit with many more words) and that it should have an "observation" column and a time index column. 

From what I can see, there still needs to be a bit more structure to having something that we can use to consistently read in the target data. I can see a few ways of addressing this:

1. mandate specific column and file names
2. add configurations to the admin schema that defines the path to the time series and oracle output data, mapping column names to targets.
3. the same as 2, but having a specific `targets.json` spec.

2024-11-15 14:53 UTC, LucieContamin commented on docs/source/user-guide/target-data.md
> +**The oracle output will contain the independent task ID variables** that are
For me the original text is clear enough. I will be ok with keeping it.

2024-11-15 17:10 UTC, zkamvar commented on docs/source/user-guide/target-data.md
> +**The oracle output will contain the independent task ID variables** that are
The original text feels a lot like legal jargon and I had a hard time understanding what it actually means.

2024-11-21 15:23 UTC, elray1 requested changes
Looks great!  I'm requesting a few minor changes.

2024-11-21 15:23 UTC, elray1 commented on docs/source/user-guide/target-data.md
> +25) with four target end dates between 2022-11-19 and 2022-12-10.
```suggestion
To make comparisons easier, we have subset the data to Massachusettes (FIPS code
25) with one `reference_date` of 2022-11-19 and four target end dates between 2022-11-19 and 2022-12-10.
```

2024-11-21 15:23 UTC, elray1 commented on docs/source/user-guide/target-data.md
> +:::{table} A subset of **model output** showing 6 `sample` predictions across one horizon
```suggestion
:::{table} A subset of **model output** showing 6 `sample` predictions at one horizon
```

2024-11-21 15:23 UTC, elray1 commented on docs/source/user-guide/target-data.md
> +2022-11-26 was `"moderate"`.
```suggestion
The presence of a `1` for the `oracle_value` in the first row and `0` in the
subsequent three rows indicates that the observed rate category in
Massachusettes on the week of 2022-11-19 was `"low"`. Similarly, the observed rate category for the week of
2022-11-26 was `"moderate"`.
```

2024-11-21 15:23 UTC, elray1 commented on docs/source/user-guide/target-data.md
> +two output types the `oracle_value` depends on the `output_type_id`. On the
```suggestion
**The `output_type` and `output_type_id` columns only need to be included if
the hub collects `pmf` or `cdf` outputs.** For those two output types the
`oracle_value` depends on the `output_type_id` (see the next section for more
detail). On the
```

2024-11-21 15:23 UTC, elray1 commented on docs/source/user-guide/target-data.md
> +model output representation columns.
```suggestion
A hub will typically have access to data in time series format, and will
need to convert it to the **oracle output** format for use with any tools
that require it in that format (see the next section). In hubs that
collect mean, median, quantile, or sample predictions for the reported
signal values in the raw time series data, the two formats may be
essentially the same, perhaps with some renaming of columns. However,
these data formats will differ more in hubs that form predictions for quantities
that are derived from the the raw time series data, such as the peak time or
peak incidence, and in hubs that collect pmf or cdf predictions.
```

2024-11-21 15:23 UTC, elray1 commented on docs/source/user-guide/target-data.md
> +model output representation columns.
See a separate comment on the PR for more about my thinking here.  I decided that maybe simpler was better in terms of just stating that the formats would differ in these situations rather than providing more detailed examples.  I'm open to further revision though!

2024-11-21 19:00 UTC, zkamvar commented on docs/source/user-guide/target-data.md
> +two output types the `oracle_value` depends on the `output_type_id`. On the
I think the "for" was a typo in there and can be removed unless we want to have it sound more prophetic than it should.

2024-11-21 19:11 UTC, zkamvar commented on docs/source/user-guide/target-data.md
> +model output representation columns.
I think this is definitely moving in the right direction!

2024-11-21 20:44 UTC, elray1 approved these changes
looks good! thanks!

2024-11-21 20:54 UTC, merged