add derived task ID language
hubverse-org/hubDocs pull request #217
Opened 2024-11-27 23:25 UTC by zkamvar

2024-12-03 14:37 UTC, annakrystalli requested changes
Thanks for putting this together! Some overall minor comments but just wanted to make sure we clarified that there are situations where derived task IDs **must** be specified for correct validation.

2024-12-03 14:37 UTC, annakrystalli commented on docs/source/user-guide/tasks.md
> +If we had 4 `horizon` values, along with the 10 `origin_dates`, we would have a total of 40 `target_date`s. There are 20,000 _unique_ combinations across 10
While the walkthrough is useful, I think it would be easier to follow with smaller example numbers. Also the point that needs to be made more clearly is that there is a one to one relationship between a derived task id and the values it depends on. For example a forecast with a given `origin_date` `"2024-11-07"` and horizon `1` has only a single valid `"arget_date` value: `"2024-11-14"`, regardless of the complete list of `target_date` tas ID values.

2024-12-03 14:37 UTC, annakrystalli commented on docs/source/user-guide/tasks.md
> +In schemas version 4.0.0, we introduced `derived_task_ids` properties to enable
```suggestion
In schema version 4.0.0, we introduced `derived_task_ids` properties to enable
```

2024-12-03 14:37 UTC, annakrystalli commented on docs/source/user-guide/tasks.md
> +significantly improve validation efficency. For more information see the
We should also highlight here in bold that, if any of the task IDs a derived task ID depends on have required values, it is essential for derived_task_ids to be specified. If this is the case and derived task IDs are not specified, the dependent nature of derived task ID values will result in false validation errors when validating required values.

2024-12-03 16:12 UTC, zkamvar commented on docs/source/user-guide/tasks.md
> +If we had 4 `horizon` values, along with the 10 `origin_dates`, we would have a total of 40 `target_date`s. There are 20,000 _unique_ combinations across 10
Done.

2024-12-03 16:12 UTC, zkamvar commented on docs/source/user-guide/tasks.md
> +significantly improve validation efficency. For more information see the
Done in a4ba755f22937ea5763c44853f068070f320e9c6

2024-12-03 16:13 UTC, zkamvar commented on docs/source/user-guide/tasks.md
> +| ----------    | --------- | ------------- | ----------------- | ------------------------ | ----------------------------------- |
```suggestion
| ------------- | --------- | ------------- | ----- | ------------------------ | ----------------------------------- |
```

2024-12-03 16:14 UTC, zkamvar commented on docs/source/user-guide/tasks.md
> +| ------------- | --------- | ------------- | ----- | ------------------------ | ----------------------------------- |
```suggestion
| ------------- | --------- | ------------- | ----- | -------------------------- | ------------------------------------- |
```

2024-12-04 09:43 UTC, annakrystalli requested changes
Thanks for the additions! I had a go at editing the first  couple of paragraphs to simplify them. Other than that I've made a suggestion that perhaps another hub admin have a look at the added detail (or even all of it for that matter!) to make sure it all makes sense. @LucieContamin perhaps?

2024-12-04 09:43 UTC, annakrystalli commented on docs/source/user-guide/tasks.md
> +must be ignored during validation.
```suggestion
Each model output task is based on unique combinations of task ID values. For example, for a given `origin_date` which is a task ID which often acts as the round ID (let's say "2024-11-07"), 2 `locations`, and 2 `horizon` values, there are 4 unique tasks (1 `origin_date` × 2 `locations` × 2 `horizon`s). 

**However, some task variables are derived directly from others.** For instance, `target_date` represents when the outcome of interest occurs and is calculated based on the `origin_date` and `horizon`. If the `origin_date` is "2024-11-07" and the `horizon` is 1 week, the `target_date` will be "2024-11-14." For a `horizon` of 2 weeks, the `target_date` will be "2024-11-21." Such task IDs therefore have **a one-to-one relationship** to values of the task IDs they are derived from.

By adding a `target_date` task ID to the above example we would still have a total of 4 unique tasks since `target_date` is derived from the `origin_date` and `horizon` task IDs and each `horizon` produces a unique valid `target_date` per location. 

While derived task IDs like `target_date` are helpful for modeling and visualization, they break assumptions made during some validation tests and can also put significant strain on validation performance. As such they should generally be ignored during standard validation and custom or optional checks added to the validation workflow to check their relationship to the task IDs they are derived from (see for example documentation on the [`opt_check_tbl_horizon_timediff()`](https://hubverse-org.github.io/hubValidations/reference/opt_check_tbl_horizon_timediff.html) used to check the time difference between values in two date columns equals a defined time period defined by values in a horizon column).
```

I've jsut tried to make things simpler and clearer

2024-12-04 09:43 UTC, annakrystalli commented on docs/source/user-guide/tasks.md
> +depend on the values of other task IDs). The higher level `derived_task_ids
```suggestion
depend on the values of other task IDs) in their hub config files. The higher level `derived_task_ids
```

2024-12-04 09:43 UTC, annakrystalli commented on docs/source/user-guide/tasks.md
> +
While I like the detail and understand it, I feel it would be useful for someone not steeped in the intricacies of `hubValidations` to confirm that the above detail is helpful rather than confusing.

2024-12-04 15:44 UTC, zkamvar commented on docs/source/user-guide/tasks.md
> +
Agreed. I was trying to convey here the specific consequences of not specifying `derived_task_ids`. I think so far we've said "it causes validation errors", but there were no examples that we could point to.

2024-12-04 16:03 UTC, annakrystalli approved these changes
Gah! Found errors in my suggestions 🙈...other than that, we're so close!...maybe it's best to just ship and ask for additional reviews after, maybe in the form of an issue?

2024-12-04 16:03 UTC, annakrystalli commented on docs/source/user-guide/tasks.md
> +**However, some task variables are derived directly from others.** For instance, `target_date` represents when the outcome of interest occurs and is calculated based on the `origin_date` and `horizon
```suggestion
**However, some task ID variables are derived directly from others.** For instance, `target_date` represents when the outcome of interest occurs and is calculated based on the `origin_date` and `horizon`. If the `origin_date` is `"2024-11-07"` and the `horizon` is 1 week, the `target_date` will be `"2024-11-14"`. For a `horizon` of 2 weeks, the `target_date` will be `"2024-11-21"`. Such task IDs therefore have **a one-to-one relationship** to values of the task IDs they are derived from.
```

2024-12-04 16:15 UTC, zkamvar commented
> Gah! Found errors in my suggestions 🙈...other than that, we're so close!...maybe it's best to just ship and ask for additional reviews after, maybe in the form of an issue?

LOL no worries! I think it's okay to wait for @LucieContamin's review since she tagged herself earlier. This topic is also not super critical as we've determined in #193 that only one public hub uses the `derived_task_ids` argument in their workflows.

2024-12-04 16:22 UTC, annakrystalli commented
Ok. It's just that the v4 release of all docs hinges on all these being merged but I guess waiting a day would be fine.

2024-12-05 15:19 UTC, LucieContamin requested changes
Thank you! I made some minor comments to add more details, or rephrase some sentences a bit, feel free to ignore.
The major issue that I have is the validation example table to me, either I misunderstood something or there is a mistake on that one, would it be possible to add more information or clarify, please?

2024-12-05 15:19 UTC, LucieContamin commented on docs/source/user-guide/tasks.md
> +Without specifying this, you will end up with a
I struggle with the first sentence a bit, minor issue but I needed it to read it multiple times to understand it, so I might suggest:

```suggestion
If any of the task IDs, which a derived task ID depends on, have `required` values, **it is essential for `derived_task_ids` to be specified**. Otherwise, this will result in false validation errors. For example, if you have two required `horizon` values of 1 and 2, then you _must_ include `target_date` in `derived_task_ids`.
Without specifying this, you will end up with a
```

2024-12-05 15:19 UTC, LucieContamin commented on docs/source/user-guide/tasks.md
> +
I don't understand the table:
- if the derived task values are correct: the validation passes whether we specify the derived information or not
- if the derived task values are incorrect:
    - the validation fail if we don't provide the derived information
    - the validation returns nothing (ignore) if we do provide the information. 
    
 It seems wrong to me and in contradiction with the "validation will provide false errors if there are unspecified derived task IDs"

2024-12-05 16:46 UTC, zkamvar commented on docs/source/user-guide/tasks.md
> +
I think this make sense!

2024-12-05 17:18 UTC, zkamvar commented on docs/source/user-guide/tasks.md
> +Without specifying this, you will end up with a
I don't think it's a minor issue. I also [struggled with the noun phrase "the task IDs a derived task ID depends on"](https://github.com/hubverse-org/hubValidations/pull/161#discussion_r1843974147). I had previously suggested "parent task ID", but [was overruled as not accurate](https://github.com/hubverse-org/hubValidations/pull/161#discussion_r1843996007). I would like to come up with a succinct descriptor of the relationship so that we can clearly label "task IDs a derived task ID depends on."

2024-12-05 18:01 UTC, zkamvar commented on docs/source/user-guide/tasks.md
> +
@LucieContamin this is exactly the kind of feedback I was looking for! The way it works for the validation is that the derived task IDs are omitted from the validation table when `derived_task_ids` is specified. 

I think it's probably best to remove the table or split it into two tables. I'll make a change and see if it works.

2024-12-05 18:04 UTC, zkamvar commented on docs/source/user-guide/tasks.md
> +Without specifying this, you will end up with a
Based on @LucieContamin's suggestion in slack: 

```suggestion
If any task IDs with `required` values have an associated derived task ID, **it is essential for `derived_task_ids` to be specified**. Otherwise, this will result in false validation errors. For example, if you have two required `horizon` values of 1 and 2, then you _must_ include `target_date` in `derived_task_ids`.
Without specifying this, you will end up with a
```

2024-12-05 18:14 UTC, zkamvar commented on docs/source/user-guide/tasks.md
> +**However, some task ID variables are derived directly from others.** For instance, `target_date` represents when the outcome of interest occurs and is calculated based on the `origin_date` and `hori
Thank you, @LucieContamin! I've cleaned up your suggestion a bit below:

```suggestion
**However, it is possible to have task ID variables that are derived directly from others.** For example, `target_date` (which represents when the outcome of interest occurs) can be calculated based on the `origin_date` and `horizon` (e.g. `origin_date + horizon * 7` to calculate weekly predictions). If the `origin_date` is `"2024-11-07"` and the `horizon` is 1 week, the `target_date` will be `"2024-11-14"`. For a `horizon` of 2 weeks, the `target_date` will be `"2024-11-21"`. Such task IDs therefore have **a one-to-one relationship** to values of the task IDs they are derived from. We strongly advise hub administrators to add the derived information and calculation in their documentation. 
```

2024-12-05 20:34 UTC, zkamvar commented on docs/source/user-guide/tasks.md
> +
I attempted a fix for this in 4cd5a567ceecb5e1b1b692a97d81136c65e9f077

2024-12-05 21:07 UTC, merged