update schema version to v4.0.0
hubverse-org/hubDocs pull request #219
Opened 2024-12-04 13:17 UTC by annakrystalli

This PR updates the schema version displayed in the interactive schema navigators in the docs.

A release of with a `4.0.0` tag should also be made once merged.

We should probably merge once #217 & #218 are merged

2024-12-04 15:48 UTC, zkamvar requested changes
There are a couple of other places in the documentation that need to be updated:


```
$ rg 3.0.1 docs/source/
docs/source/conf.py
84:schema_version = "v3.0.1"

docs/source/overview/cite.md
6:The Consortium of Infectious Disease Modeling Hubs. The hubverse: open tools for collaborative modeling. GitHub release v3.0.1, 5 Aug 2024. URL: https://github.com/hubverse-org  

docs/source/user-guide/model-output.md
440:  "schema_version": "https://raw.githubusercontent.com/hubverse-org/schemas/main/v3.0.1/tasks-schema.json",

docs/source/quickstart-hub-admin/tasks-config.md
260:  "schema_version": "https://raw.githubusercontent.com/hubverse-org/schemas/main/v3.0.1/tasks-schema.json",
```

2024-12-04 15:57 UTC, annakrystalli commented
I have made the critical version instances that require updating to update automatically. The schema versions are not critical to the above examples so to avoid having to update them every version update, I've just added a `*` to the version to make them version agnostic in e3523847d03c579e395a115c372395f9a8d425d6

2024-12-04 16:02 UTC, zkamvar approved these changes

2024-12-10 09:59 UTC, annakrystalli commented
Am merging this because the text on output type IDs currently doesn't match the interactive schema displayed. We can do the actual release when #220 an #222 are merged.

2024-12-10 10:00 UTC, merged